### ISSUE TITLE
[BUG][SNAKE]

### ISSUE THREAD

**Issue by Dremoros** [feedthejim/effective-barnacle#3]
Hello,

When a player is too big and fill up the entire screen the game bug and it's impossible to access it back.
(the game bugged when the snake was at 13101 points if that is of any help).

Sincerely,

-- 
Arthur Kluytmans

**Comment by feedthejim** [comment]
Hi,

Fail nétiquette :).

Should be kinda fixed.

Best,

-- 
Jimmy
